#######################################
# required
#######################################
elasticsearch:
  node: "YOUR ES HOST AND PORT"
  auth:
    username: "username"
    password: "password"
#######################################
# optional overrides
#######################################
# cycles:
#   continuous: false
#   n: false
#   ms_pause_after_each: 30000
# n_pod_hosts: 3
# n_pods: 30
# pod_metrics:
#   cpu:
#     mean: 0.4
#     stdev: 0.2
#   memory:
#     mean: 0.5
#     stdev: 0.1
